language: ruby
rvm:
- 2.5.1

script: 
  - "bundle exec jekyll build"
  - "ruby make_pdf.rb"

branches:
  only:
  - gh-pages

addons:
  apt:
    sources:
      - pov-wkhtmltopdf
    packages:
      - wkhtmltopdf

install:
  - "bundle install"
  - "gem install pdfkit"
    
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file: "./_site/cv.pdf"
  skip_cleanup: true
  on:
    tags: true

