sudo: required
dist: trusty
language: ruby
rvm:
- 2.5.1

script: 
  - "bundle exec jekyll build"
  - "ruby make_pdf.rb"

branches:
  only:
  - gh-pages

    #addons:
    #apt:
    #sources:
    #  - pov-wkhtmltopdf
    #packages:
    #  - wkhtmltopdf

install:
  - "bundle install"
  - "gem install pdfkit"
    
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sudo apt-get -qq update
  - sudo apt-get install -y xfonts-75dpi
  - wget http://download.gna.org/wkhtmltopdf/0.12/0.12.2/wkhtmltox-0.12.2_linux-trusty-amd64.deb
  - sudo dpkg -i wkhtmltox-0.12.2_linux-trusty-amd64.deb

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: "./_site/cv.pdf"
  skip_cleanup: true
  on:
    branch: gh-pages
